version: '3'

services:
  pgsql:
    image: postgres:latest
    ports:
      - '5432:5432'
    container_name: 'pgsql'
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pgdatabase

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
